# Generated by Django 4.1.3 on 2022-12-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyCovidRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=128)),
                ('country_id', models.CharField(max_length=50)),
                ('total_confirmed_cases', models.IntegerField()),
                ('total_deaths_cases', models.IntegerField()),
                ('total_recovered_cases', models.IntegerField()),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
