# Generated by Django 4.1.3 on 2022-12-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycovidrecord',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mycovidrecord',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
