# Generated by Django 4.1.3 on 2022-12-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_mycovidrecord_created_date_alter_mycovidrecord_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycovidrecord',
            name='country_name',
            field=models.CharField(default='jordan', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='mycovidrecord',
            unique_together={('unique_id', 'country_id')},
        ),
    ]
